apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: tickiting
build:
  artifacts:
    - image: saikatms/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: saikatms/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: saikatms/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: saikatms/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: saikatms/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: saikatms/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/tickets-depl.yaml
    - infra/k8s/tickets-mongo-depl.yaml
    - infra/k8s/nats-depl.yaml
    - infra/k8s/orders-mongo-depl.yaml
    - infra/k8s/orders-depl.yaml
    - infra/k8s/expiration-redis-depl.yaml
    - infra/k8s/expiration-depl.yaml
    - infra/k8s/payments-depl.yaml
    - infra/k8s/payments-mongo-depl.yaml
